export { default as Header } from './header'
export { default as About } from './about'
export { default as Projects } from './projects'
export { default as Resume } from './resume'
export { default as Test } from './Test'
